export const actionType = {
  LOAD: "LOAD",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER_ACCOUNT: "REGISTER_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
  RESET_NOTIFICATION: "RESET_NOTIFICATION",
};

export const asyncActionState = {
  FULFILLED: "FULFILLED",
  PENDING: "PENDING",
  REJECTED: "REJECTED",
};
